#!/usr/bin/env python3
"""
Test HTTPS receiver with mTLS (mutual TLS) support.
Receives log batches from Flicker over HTTPS and requires client certificate authentication.

Usage:
    ./test-mtls-receiver.py [--port PORT] [--host HOST]

This server requires certificates generated by generate-test-certs.sh
"""

import ssl
import json
import argparse
from http.server import HTTPServer, BaseHTTPRequestHandler
from datetime import datetime
import gzip
from io import BytesIO

# ANSI color codes for pretty output
CYAN = '\033[96m'
GREEN = '\033[92m'
YELLOW = '\033[93m'
RED = '\033[91m'
BLUE = '\033[94m'
MAGENTA = '\033[95m'
RESET = '\033[0m'
BOLD = '\033[1m'


class MTLSLogReceiver(BaseHTTPRequestHandler):
    """HTTP request handler that processes log batches with mTLS authentication"""

    # Counter for batches received
    batch_counter = 0

    def do_POST(self):
        """Handle POST requests with log batches"""

        # Get client certificate info
        client_cert = self.connection.getpeercert()
        client_subject = dict(x[0] for x in client_cert['subject'])
        client_cn = client_subject.get('commonName', 'Unknown')

        MTLSLogReceiver.batch_counter += 1

        # Get content length
        content_length = int(self.headers.get('Content-Length', 0))

        # Check for gzip compression
        content_encoding = self.headers.get('Content-Encoding', '').lower()
        is_compressed = content_encoding == 'gzip'

        # Read request body
        body = self.request.recv(content_length)

        # Decompress if needed
        if is_compressed:
            print(f"{BLUE}[COMPRESSED]{RESET} Received {len(body)} bytes (gzip)")
            try:
                buf = BytesIO(body)
                with gzip.GzipFile(fileobj=buf, mode='rb') as f:
                    body = f.read()
                print(f"{BLUE}[COMPRESSED]{RESET} Decompressed to {len(body)} bytes")
            except Exception as e:
                print(f"{RED}[ERROR]{RESET} Failed to decompress: {e}")
                self.send_response(400)
                self.end_headers()
                return

        # Parse JSON
        try:
            entries = json.loads(body.decode('utf-8'))
        except json.JSONDecodeError as e:
            print(f"{RED}[ERROR]{RESET} Invalid JSON: {e}")
            self.send_response(400)
            self.end_headers()
            return

        # Print batch info with mTLS client info
        timestamp = datetime.now().strftime('%H:%M:%S')
        print(f"\n{BOLD}{CYAN}[BATCH #{MTLSLogReceiver.batch_counter}]{RESET} "
              f"{timestamp} - {len(entries)} entries "
              f"{GREEN}[mTLS: {client_cn}]{RESET}")

        # Print each log entry
        for i, entry in enumerate(entries, 1):
            path = entry.get('path', 'unknown')
            line = entry.get('line', '')

            # Truncate long lines
            if len(line) > 200:
                line = line[:200] + '...'

            print(f"  {YELLOW}[{i}]{RESET} {MAGENTA}{path}{RESET}")
            print(f"      {line}")

        # Send success response
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        response = json.dumps({'status': 'ok', 'received': len(entries)})
        self.wfile.write(response.encode('utf-8'))

    def log_message(self, format, *args):
        """Suppress default HTTP logging"""
        pass


def create_mtls_server(host, port, cert_dir=None):
    """Create an HTTPS server with mTLS (client certificate verification)"""

    # Check if certificates exist
    import os

    # Auto-detect cert directory
    if cert_dir is None:
        # Try current directory first (for running from test_tools/)
        if os.path.exists("certs/server.crt"):
            cert_dir = "certs"
        # Try test_tools/certs (for running from project root)
        elif os.path.exists("test_tools/certs/server.crt"):
            cert_dir = "test_tools/certs"
        else:
            print(f"{RED}[ERROR]{RESET} Certificate files not found")
            print(f"Please run: ./test_tools/generate-test-certs.sh")
            return None

    server_cert = f"{cert_dir}/server.crt"
    server_key = f"{cert_dir}/server.key"
    ca_cert = f"{cert_dir}/ca.crt"

    if not all(os.path.exists(f) for f in [server_cert, server_key, ca_cert]):
        print(f"{RED}[ERROR]{RESET} Certificate files not found in {cert_dir}/")
        print(f"Please run: ./test_tools/generate-test-certs.sh")
        return None

    # Create HTTPS server
    httpd = HTTPServer((host, port), MTLSLogReceiver)

    # Create SSL context with client certificate verification
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)

    # Load server certificate and key
    context.load_cert_chain(certfile=server_cert, keyfile=server_key)

    # Load CA certificate for client verification
    context.load_verify_locations(cafile=ca_cert)

    # Require client certificate (this enables mTLS)
    context.verify_mode = ssl.CERT_REQUIRED

    # Wrap the socket with SSL
    httpd.socket = context.wrap_socket(httpd.socket, server_side=True)

    return httpd


def main():
    parser = argparse.ArgumentParser(description='HTTPS receiver with mTLS for Flicker testing')
    parser.add_argument('--port', type=int, default=8443, help='Port to listen on (default: 8443)')
    parser.add_argument('--host', type=str, default='localhost', help='Host to bind to (default: localhost)')

    args = parser.parse_args()

    print(f"{BOLD}{GREEN}Flicker mTLS Test Receiver{RESET}")
    print(f"{CYAN}{'=' * 50}{RESET}")

    # Create server
    httpd = create_mtls_server(args.host, args.port)
    if httpd is None:
        return 1

    print(f"{GREEN}[READY]{RESET} HTTPS server with mTLS listening on https://{args.host}:{args.port}")
    print(f"{GREEN}[READY]{RESET} Waiting for log batches from Flicker...")
    print(f"{GREEN}[READY]{RESET} Client certificate verification: ENABLED")
    print(f"{CYAN}{'=' * 50}{RESET}\n")

    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print(f"\n\n{YELLOW}[SHUTDOWN]{RESET} Server stopped by user")
        total = MTLSLogReceiver.batch_counter
        print(f"{GREEN}[STATS]{RESET} Total batches received: {total}")
        return 0


if __name__ == '__main__':
    exit(main())
